mode = "dark"
accent = "#ADC4DA"
selection = "#354E65"
selection_foreground = "#E1E9F0"
selection_background = "#354E65"
muted = "#90A6BB"
background = "#101C29"
dark_background = "#0C1621"
darker_background = "#09111A"
lighter_background = "#1C2B3D"
foreground = "#CBD7E2"
dark_foreground = "#90A6BB"
light_foreground = "#ACBED0"
bright_foreground = "#E1E9F0"
hyprland_active_border = "#ADC4DA"
hyprland_inactive_border = "#425970"
red = "#CBD7E2"
green = "#ADC4DA"
yellow = "#ACBED0"
orange = "#ACBED0"
blue = "#ADC4DA"
magenta = "#CBD7E2"
cyan = "#90A6BB"
brown = "#90A6BB"
bright_red = "#E1E9F0"
bright_green = "#CBD7E2"
bright_yellow = "#E1E9F0"
bright_blue = "#ACBED0"
bright_magenta = "#CBD7E2"
bright_cyan = "#ADC4DA"
